#ifndef __ARDUINO_COMPATIBILITY_H__
#define __ARDUINO_COMPATIBILITY_H__

#include <avr/io.h>

#define DIGITAL_0_PIN 1 << 0
#define DIGITAL_1_PIN 1 << 1
#define DIGITAL_2_PIN 1 << 2
#define DIGITAL_3_PIN 1 << 3
#define DIGITAL_4_PIN 1 << 4
#define DIGITAL_5_PIN 1 << 5
#define DIGITAL_6_PIN 1 << 6
#define DIGITAL_7_PIN 1 << 7

#define DIGITAL_8_PIN 1 << 0
#define DIGITAL_9_PIN 1 << 1
#define DIGITAL_10_PIN 1 << 2
#define DIGITAL_11_PIN 1 << 3
#define DIGITAL_12_PIN 1 << 4
#define DIGITAL_13_PIN 1 << 5

#define DIGITAL_0_MODE DDRD
#define DIGITAL_1_MODE DDRD
#define DIGITAL_2_MODE DDRD
#define DIGITAL_3_MODE DDRD
#define DIGITAL_4_MODE DDRD
#define DIGITAL_5_MODE DDRD
#define DIGITAL_6_MODE DDRD
#define DIGITAL_7_MODE DDRD

#define DIGITAL_8_MODE DDRB
#define DIGITAL_9_MODE DDRB
#define DIGITAL_10_MODE DDRB
#define DIGITAL_11_MODE DDRB
#define DIGITAL_12_MODE DDRB
#define DIGITAL_13_MODE DDRB

#define DIGITAL_0_PORT PORTD
#define DIGITAL_1_PORT PORTD
#define DIGITAL_2_PORT PORTD
#define DIGITAL_3_PORT PORTD
#define DIGITAL_4_PORT PORTD
#define DIGITAL_5_PORT PORTD
#define DIGITAL_6_PORT PORTD
#define DIGITAL_7_PORT PORTD

#define DIGITAL_8_PORT PORTB
#define DIGITAL_9_PORT PORTB
#define DIGITAL_10_PORT PORTB
#define DIGITAL_11_PORT PORTB
#define DIGITAL_12_PORT PORTB
#define DIGITAL_13_PORT PORTB

#define PIN_MODE_0_OUTPUT DIGITAL_0_MODE |= DIGITAL_0_PIN
#define PIN_MODE_1_OUTPUT DIGITAL_1_MODE |= DIGITAL_1_PIN
#define PIN_MODE_2_OUTPUT DIGITAL_2_MODE |= DIGITAL_2_PIN
#define PIN_MODE_3_OUTPUT DIGITAL_3_MODE |= DIGITAL_3_PIN
#define PIN_MODE_4_OUTPUT DIGITAL_4_MODE |= DIGITAL_4_PIN
#define PIN_MODE_5_OUTPUT DIGITAL_5_MODE |= DIGITAL_5_PIN
#define PIN_MODE_6_OUTPUT DIGITAL_6_MODE |= DIGITAL_6_PIN
#define PIN_MODE_7_OUTPUT DIGITAL_7_MODE |= DIGITAL_7_PIN
#define PIN_MODE_8_OUTPUT DIGITAL_8_MODE |= DIGITAL_8_PIN
#define PIN_MODE_9_OUTPUT DIGITAL_9_MODE |= DIGITAL_9_PIN
#define PIN_MODE_10_OUTPUT DIGITAL_10_MODE |= DIGITAL_10_PIN
#define PIN_MODE_11_OUTPUT DIGITAL_11_MODE |= DIGITAL_11_PIN
#define PIN_MODE_12_OUTPUT DIGITAL_12_MODE |= DIGITAL_12_PIN
#define PIN_MODE_13_OUTPUT DIGITAL_13_MODE |= DIGITAL_13_PIN

#define DIGITAL_WRITE_0_HIGH PORTD |= 1 << 0
#define DIGITAL_WRITE_1_HIGH PORTD |= 1 << 1
#define DIGITAL_WRITE_2_HIGH PORTD |= 1 << 2
#define DIGITAL_WRITE_3_HIGH PORTD |= 1 << 3
#define DIGITAL_WRITE_4_HIGH PORTD |= 1 << 4
#define DIGITAL_WRITE_5_HIGH PORTD |= 1 << 5
#define DIGITAL_WRITE_6_HIGH PORTD |= 1 << 6
#define DIGITAL_WRITE_7_HIGH PORTD |= 1 << 7
#define DIGITAL_WRITE_8_HIGH PORTB |= 1 << 0
#define DIGITAL_WRITE_9_HIGH PORTB |= 1 << 1
#define DIGITAL_WRITE_10_HIGH PORTB |= 1 << 2
#define DIGITAL_WRITE_11_HIGH PORTB |= 1 << 3
#define DIGITAL_WRITE_12_HIGH PORTB |= 1 << 4
#define DIGITAL_WRITE_13_HIGH PORTB |= 1 << 5


#define DIGITAL_WRITE_0_LOW PORTD &= ~(1 << 0)
#define DIGITAL_WRITE_1_LOW PORTD &= ~(1 << 1)
#define DIGITAL_WRITE_2_LOW PORTD &= ~(1 << 2)
#define DIGITAL_WRITE_3_LOW PORTD &= ~(1 << 3)
#define DIGITAL_WRITE_4_LOW PORTD &= ~(1 << 4)
#define DIGITAL_WRITE_5_LOW PORTD &= ~(1 << 5)
#define DIGITAL_WRITE_6_LOW PORTD &= ~(1 << 6)
#define DIGITAL_WRITE_7_LOW PORTD &= ~(1 << 7)
#define DIGITAL_WRITE_8_LOW PORTB &= ~(1 << 0)
#define DIGITAL_WRITE_9_LOW PORTB &= ~(1 << 1)
#define DIGITAL_WRITE_10_LOW PORTB &= ~(1 << 2)
#define DIGITAL_WRITE_11_LOW PORTB &= ~(1 << 3)
#define DIGITAL_WRITE_12_LOW PORTB &= ~(1 << 4)
#define DIGITAL_WRITE_13_LOW PORTB &= ~(1 << 5)


#define DIGITAL_READ_0 PORTD & (1 << 0)
#define DIGITAL_READ_1 PORTD & (1 << 1)
#define DIGITAL_READ_2 PORTD & (1 << 2)
#define DIGITAL_READ_3 PORTD & (1 << 3)
#define DIGITAL_READ_4 PORTD & (1 << 4)
#define DIGITAL_READ_5 PORTD & (1 << 5)
#define DIGITAL_READ_6 PORTD & (1 << 6)
#define DIGITAL_READ_7 PORTD & (1 << 7)
#define DIGITAL_READ_8 PORTB & (1 << 0)
#define DIGITAL_READ_9 PORTB & (1 << 1)
#define DIGITAL_READ_10 PORTB & (1 << 2)
#define DIGITAL_READ_11 PORTB & (1 << 3)
#define DIGITAL_READ_12 PORTB & (1 << 4)
#define DIGITAL_READ_13 PORTB & (1 << 5)


#endif /* __ARDUINO_COMPATIBILITY_H__ */
